-- Create the table for bookings
create table bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  
  -- Service Details
  service_id text,
  service_name text,
  frequency text,
  duration integer,
  price numeric,
  
  -- Schedule
  date date,
  time time,
  
  -- Customer Info
  name text,
  email text,
  phone text,
  
  -- Location
  address text,
  canton text,
  
  -- Extra
  observations text,
  service_details jsonb
);

-- Set up Row Level Security (RLS)
alter table bookings enable row level security;

-- Policy: Allow anyone (anon) to insert bookings
-- (In a real app, you might restrict this or add captcha)
create policy "Enable insert for everyone"
on bookings for insert
to anon
with check (true);


